// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ninja_manager.Models;

#nullable disable

namespace ninja_manager.Migrations
{
    [DbContext(typeof(NinjaContext))]
    [Migration("20231008130747_newdatabase")]
    partial class newdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory", b =>
                {
                    b.Property<int>("NinjaId")
                        .HasColumnType("int")
                        .HasColumnName("ninja_id");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    b.HasKey("NinjaId", "EquipmentId")
                        .HasName("PK__inventor__18BDFAEEC7A06D30");

                    b.HasIndex("EquipmentId");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("ninja_manager.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int")
                        .HasColumnName("agility");

                    b.Property<double>("Category")
                        .HasColumnType("float")
                        .HasColumnName("category");

                    b.Property<double>("Gold")
                        .HasColumnType("float")
                        .HasColumnName("gold");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int")
                        .HasColumnName("intelligence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("Strength")
                        .HasColumnType("int")
                        .HasColumnName("strength");

                    b.HasKey("Id");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("ninja_manager.Models.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int")
                        .HasColumnName("agility");

                    b.Property<double>("Gold")
                        .HasColumnType("float")
                        .HasColumnName("gold");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int")
                        .HasColumnName("intelligence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("Strength")
                        .HasColumnType("int")
                        .HasColumnName("strength");

                    b.HasKey("Id");

                    b.ToTable("ninja", (string)null);
                });

            modelBuilder.Entity("Inventory", b =>
                {
                    b.HasOne("ninja_manager.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .IsRequired()
                        .HasConstraintName("FK__inventory__equip__3C69FB99");

                    b.HasOne("ninja_manager.Models.Ninja", null)
                        .WithMany()
                        .HasForeignKey("NinjaId")
                        .IsRequired()
                        .HasConstraintName("FK__inventory__ninja__3B75D760");
                });
#pragma warning restore 612, 618
        }
    }
}
